apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldrule-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shieldrule-web
      role: shieldrule-web-role
  strategy: {}
  template:
    metadata:
      labels:
        app: shieldrule-web
        role: shieldrule-web-role
    spec:
      {{ if .Values.service_account_role }}
      serviceAccountName: aws-role
      {{ end }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      initContainers:
        - name: volume-mount-hack
          imagePullPolicy: Always
          image: "{{ .Values.web_image_url }}:{{ .Values.SHIELDRULE_ENVIRONMENT }}"
          command: [ "sh", "-c", "cp -r /usr/share/nginx/html/* /usr/share/nginx/html_rw/ && cp ./nginx.eks.conf /etc/nginx/conf.d/default.conf" ]
          volumeMounts:
            - mountPath: /usr/share/nginx/html_rw
              name: shieldrule-web-nginx-html
            - mountPath: /etc/nginx/conf.d/
              name: shieldrule-web-nginx-config
      containers:
        - image: "{{ .Values.web_image_url }}:{{ .Values.SHIELDRULE_ENVIRONMENT }}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "./load-env.sh /usr/share/nginx/html_rw/config.js && nginx -g \"daemon off;\""]
          name: shieldrule-web
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 90
          resources:
            requests:
              memory: {{ .Values.web.resources.requests.memory }}
              cpu: {{ .Values.web.resources.requests.cpu }}
            limits:
              memory: {{ .Values.web.resources.limits.memory }}
              cpu: {{ .Values.web.resources.limits.cpu }}
          securityContext:
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: shieldrule-web-nginx-cache
            - mountPath: /usr/share/nginx/html_rw
              name: shieldrule-web-nginx-html
            - mountPath: /etc/nginx/conf.d/
              name: shieldrule-web-nginx-config
          envFrom:
            - secretRef:
                name: api-secret
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.POSTGRES_HOST| quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.POSTGRES_PORT | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB | quote }}
            - name: AUDIENCE_URL
              value: {{ .Values.AUDIENCE_URL | quote }}
            - name: ISSUER_URL
              value: {{ .Values.ISSUER_URL | quote }}
            - name: AUTH0_ENVIRONMENT_PREFIX
              value: {{ .Values.AUTH0_ENVIRONMENT_PREFIX | quote }}
            - name: RESET_DB
              value: {{ .Values.RESET_DB | quote }}
            - name: USE_AUTH_0
              value: {{ .Values.USE_AUTH_0 | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.ENVIRONMENT | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.SENTRY_ENVIRONMENT | quote }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.METRICS_NAMESPACE | quote }}
            - name: SLACK_REDIRECT_URI
              value: {{ .Values.SLACK_REDIRECT_URI | quote }}
            - name: SHIELDRULE_ENVIRONMENT
              value: {{ .Values.SHIELDRULE_ENVIRONMENT | quote }}
            - name: USE_INSTANCE_PROFILE
              value: {{ .Values.USE_INSTANCE_PROFILE | quote }}
            - name: SERVER_BUCKET
              value: {{ .Values.SERVER_BUCKET | quote }}
            - name: REDIS_HOST
              value: {{ .Values.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.REDIS_PORT | quote }}
            - name: USE_REDIS
              value: {{ .Values.USE_REDIS | quote }}
            - name: USE_SQS
              value: {{ .Values.USE_SQS | quote }}
            - name: SQS_QUEUE_NAME
              value: {{ .Values.SQS_QUEUE_NAME | quote }}
            - name: SQS_URL
              value: {{ .Values.SQS_URL | quote }}
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: shieldrule-web-nginx-cache
        - emptyDir: { }
          name: shieldrule-web-nginx-config
        - emptyDir: {}
          name: shieldrule-web-nginx-html
status: {}