apiVersion: v1
kind: Service
metadata:
  name: shieldrule-web-service
spec:
  type: NodePort
  selector:
    app: shieldrule-web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.ports.web }}
